# For a given pose velocity and global_plan, run the local planner and return full results
geometry_msgs/PoseStamped pose
nav_2d_msgs/Twist2D velocity
nav_msgs/Path global_plan
---
LocalPlanEvaluation results
