# Process a rectangular region

# reference point [m]
geometry_msgs/Point reference

# Width and height of the rectangle [m]
float64 width
float64 height

# Clockwise rotation of the rectangle [rad]
float64 rotation

# Offset coupled with rotation
geometry_msgs/Point offset
---
bool was_successful
