map_server:
    ros__parameters:
        resolution: 0.050000
        negate: 0
        occupied_thresh: 0.65
        free_thresh: 0.196
        mode: "trinary"
        image: test_map.pgm
        origin: [-15.400000, -12.200000, 0.000000]
        map_type: "occupancy"

