#!/bin/bash
set -ex

export FROM_IMAGE=osrf/ros2:testing
export UNDERLAY_MIXINS="release ccache"

docker build \
    --target builder \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg UNDERLAY_MIXINS \
    --file ../../Dockerfile ../../.
