#!/bin/bash
FROM_IMAGE=osrf/ros2:nightly
FAIL_ON_BUILD_FAILURE=""
UNDERLAY_MIXINS="debug ccache"
OVERLAY_MIXINS="debug ccache coverage-gcc"
docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg UNDERLAY_MIXINS \
    --build-arg OVERLAY_MIXINS \
    --file ./Dockerfile ../../.