// Copyright (c) 2024 OTSAW

#ifndef NAV2_MPPI_CONTROLLER__CUDA__OTSAW_CRITIC_GPU_CUH_
#define NAV2_MPPI_CONTROLLER__CUDA__OTSAW_CRITIC_GPU_CUH_

float test_gpu_fn();

#endif  // NAV2_MPPI_CONTROLLER__CUDA__OTSAW_CRITIC_GPU_CUH_
