// Copyright (c) 2026, Jiarui Zou
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// This file is generated by AI.
#include <limits>
#include <memory>
#include <vector>

#include "gtest/gtest.h"
#include "nav2_costmap_2d/costmap_2d.hpp"
#include "nav2_navfn_planner/navfn.hpp"
#include "nav2_navfn_planner/navfn_planner.hpp"


namespace
{

class TestableNavfnPlanner : public nav2_navfn_planner::NavfnPlanner
{
public:
  using NavfnPlanner::getPlanFromPotential;

  void initializeForTest(
    nav2_costmap_2d::Costmap2D * costmap,
    double max_cycles_factor)
  {
    costmap_ = costmap;
    planner_ = std::make_unique<nav2_navfn_planner::NavFn>(
      costmap_->getSizeInCellsX(),
      costmap_->getSizeInCellsY());

    test_params_.max_cycles_factor = max_cycles_factor;
    params_ = &test_params_;
  }

private:
  nav2_navfn_planner::Parameters test_params_{};
};

}  // namespace

TEST(NavFnTest, PathExtractionCycleLimit)
{
  constexpr int map_size = 20;

  nav2_navfn_planner::NavFn navfn(map_size, map_size);
  std::vector<unsigned char> costmap(map_size * map_size, 0);

  int goal[2] = {2, 10};
  int start[2] = {10, 10};

  navfn.setCostmap(costmap.data());
  navfn.setGoal(goal);
  navfn.setStart(start);

  ASSERT_TRUE(
    navfn.calcNavFnDijkstra(
      []() {return false;}, true));

  // The potential is valid, but one extraction cycle cannot reach the goal.
  EXPECT_EQ(navfn.calcPath(1), 0);

  // A sufficient cycle budget extracts the complete path.
  EXPECT_GT(navfn.calcPath(map_size * 4), 0);
}

TEST(NavfnPlannerTest, RejectsCycleLimitOutsideIntRange)
{
  constexpr int map_size = 20;

  nav2_costmap_2d::Costmap2D costmap(
    map_size, map_size, 1.0, 0.0, 0.0);

  TestableNavfnPlanner planner;
  planner.initializeForTest(
    &costmap,
    static_cast<double>(std::numeric_limits<int>::max()));

  geometry_msgs::msg::Pose goal;
  goal.position.x = 5.0;
  goal.position.y = 5.0;

  nav_msgs::msg::Path path;

  EXPECT_FALSE(planner.getPlanFromPotential(goal, path));
}
