# Get the costmap
# TODO(orduno): the request msg can have a field to define the layer of costmap to send
#               for now we're sending the Master (aggreagate) layer
---
nav2_msgs/Costmap map
# Costmap map