#!/bin/bash
set -ex

export ROS_DISTRO=${SOURCE_BRANCH%"-devel"}
export FROM_IMAGE=ros:${ROS_DISTRO}

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE="" \
    --file ./Dockerfile ../../.
