# Error codes
# Note: The expected priority order of the errors should match the message order
int16 NONE=0
int16 UNKNOWN=3000
int16 TF_ERROR=3001
int16 START_OUTSIDE_MAP=3002
int16 GOAL_OUTSIDE_MAP=3003
int16 START_OCCUPIED=3004
int16 GOAL_OCCUPIED=3005
int16 TIMEOUT=3006
int16 NO_VALID_PATH=3007
int16 NO_VIAPOINTS_GIVEN=3008

#goal definition
geometry_msgs/PoseStamped[] goals
geometry_msgs/PoseStamped start
string planner_id
bool use_start # If false, use current robot pose as path start, if true, use start above instead
---
#result definition
nav_msgs/Path path
builtin_interfaces/Duration planning_time
int16 error_code
---
#feedback definition
