# Error codes
# Note: The expected priority order of the errors should match the message order
int16 NONE=1000
int16 UNKNOWN=1001
int16 TF_ERROR=1002
int16 START_OUTSIDE_MAP=1003
int16 GOAL_OUTSIDE_MAP=1004
int16 START_OCCUPIED=1005
int16 GOAL_OCCUPIED=1006
int16 TIMEOUT=1007
int16 NO_VALID_PATH=1008

#goal definition
geometry_msgs/PoseStamped goal
geometry_msgs/PoseStamped start
string planner_id
bool use_start # If false, use current robot pose as path start, if true, use start above instead
---
#result definition
nav_msgs/Path path
builtin_interfaces/Duration planning_time
int16 error_code
---
#feedback definition
