#goal definition
uint8 CARTESIAN = 0
uint8 GEOGRAPHIC = 1
uint8 reference_mode

nav_msgs/Path cartesian_path
geometry_msgs/PoseStamped[] start_cartesian_poses

geographic_msgs/GeoPath geographic_path
geographic_msgs/GeoPoseStamped[] start_geographic_poses

string planner_id
bool use_start_poses

string[] robot_ids
---
#result definition
nav2_msgs/PathAndBoundary path_and_boundary
builtin_interfaces/Duration planning_time
---
#feedback
