#goal definition
uint8 LOCAL = 0
uint8 GLOBAL = 1
uint8 mode

nav_msgs/Path goals_local
geometry_msgs/PoseStamped start_local

geographic_msgs/GeoPath goals_global
geographic_msgs/GeoPoseStamped start_global

string planner_id
bool use_start # If true, use current robot pose as path start, if false, use start above instead
---
#result definition
nav2_msgs/PathAndBoundary path_and_boundary
builtin_interfaces/Duration planning_time
---
#feedback
