# Error codes
# Note: The expected priority order of the errors should match the message order
int16 NONE=0
int16 UNKNOWN=6000
int16 TASK_EXECUTOR_FAILED=6001

#goal definition
geometry_msgs/PoseStamped[] poses
---
#result definition
int32[] missed_waypoints
int16[] error_codes
---
#feedback definition
uint32 current_waypoint
