#goal definition
nav_msgs/Path path
string controller_id
bool free_goal_vel
string goal_checker_id
---
#result definition
std_msgs/Empty result
---
#feedback definition
float32 distance_to_goal
float32 speed
