costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 1  # Speed zone filter type
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/speed_filter_mask"
    base: 100.0
    multiplier: -1.0
filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/speed_filter_mask"
    # TODO: Update this below line properly as relative path from package directory.
    # yaml_filename: "/path/to/speed_zone_filter.yaml"
    # Map File is added Dynamically in speed_filter_launch.py
