#!/bin/bash
set -ex

export FROM_IMAGE=osrf/ros2:nightly
export FAIL_ON_BUILD_FAILURE=""
export UNDERLAY_MIXINS="release ccache"
export OVERLAY_MIXINS="release ccache"

docker build \
    --tag ${IMAGE_NAME} \
    --build-arg FROM_IMAGE \
    --build-arg FAIL_ON_BUILD_FAILURE \
    --build-arg UNDERLAY_MIXINS \
    --build-arg OVERLAY_MIXINS \
    --file ./Dockerfile ../../.
