@startuml
skinparam backgroundcolor transparent
component dai
package drivers {
  component "apl-ssp" as ssp
}
database ".data" {
  component "struct dai ssp[3]" as d_ssp
}
database ".rodata" {
  component ssp_ops
}

dai ..> d_ssp : expose via dai_get()
d_ssp -> ssp_ops : links to
ssp ..> ssp_ops : provide
@enduml
