#! /usr/bin/env python3
# Copyright 2025 Arjo Chakravarty
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from builtin_interfaces.msg import Time
from nav2_msgs.msg import Costmap
from nav2_simple_commander.costmap_2d import PyCostmap2D
import numpy as np


# Tests generated by AI and checked by human
class TestPyCostmap2DConstructor:

    def test_init_with_nav2_costmap(self) -> None:
        """Test initialization using a nav2_msgs/Costmap."""
        msg = Costmap()
        msg.header.frame_id = 'odom'
        msg.header.stamp = Time(sec=100, nanosec=0)
        msg.metadata.size_x = 5
        msg.metadata.size_y = 5
        msg.metadata.resolution = 0.1
        msg.metadata.origin.position.x = -1.0
        msg.metadata.origin.position.y = -1.0
        # 5x5 = 25 elements
        msg.data = [255] * 25
        py_map = PyCostmap2D(msg)

        assert py_map.size_x == 5
        assert py_map.size_y == 5
        assert py_map.global_frame_id == 'odom'
        assert py_map.origin_x == -1.0
        assert py_map.origin_y == -1.0
        assert py_map.costmap[0] == 255
        assert py_map.costmap.shape == (25,)
        assert isinstance(py_map.costmap, np.ndarray)
        assert py_map.costmap.dtype == np.uint8
