#! /usr/bin/env python3
# Copyright 2025 Arjo Chakravarty
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from builtin_interfaces.msg import Time
from nav2_msgs.msg import Costmap
from nav2_simple_commander.costmap_2d import PyCostmap2D
from nav_msgs.msg import OccupancyGrid


import numpy as np


# Tests generated by AI and checked by human
class TestPyCostmap2DConstructor:

    def test_init_with_occupancy_grid(self):
        """Test initialization using a standard nav_msgs/OccupancyGrid."""
        msg = OccupancyGrid()
        msg.header.frame_id = 'map'
        msg.header.stamp = Time(sec=10, nanosec=500)
        msg.info.width = 10
        msg.info.height = 20
        msg.info.resolution = 0.5
        msg.info.origin.position.x = 1.0
        msg.info.origin.position.y = 2.0
        msg.data = [0] * (msg.info.width * msg.info.height)
        msg.data[0] = 100  # Set one specific value
        py_map = PyCostmap2D(msg)

        assert py_map.size_x == 10
        assert py_map.size_y == 20
        assert py_map.resolution == 0.5
        assert py_map.origin_x == 1.0
        assert py_map.origin_y == 2.0
        assert py_map.global_frame_id == 'map'
        assert py_map.costmap_timestamp.sec == 10
        assert py_map.costmap[0] == 100
        assert isinstance(py_map.costmap, np.ndarray)
        assert py_map.costmap.dtype == np.uint8

    def test_init_with_nav2_costmap(self):
        """Test initialization using a nav2_msgs/Costmap."""
        msg = Costmap()
        msg.header.frame_id = 'odom'
        msg.header.stamp = Time(sec=100, nanosec=0)
        msg.metadata.size_x = 5
        msg.metadata.size_y = 5
        msg.metadata.resolution = 0.1
        msg.metadata.origin.position.x = -1.0
        msg.metadata.origin.position.y = -1.0
        # 5x5 = 25 elements
        msg.data = [255] * 25
        py_map = PyCostmap2D(msg)

        assert py_map.size_x == 5
        assert py_map.size_y == 5
        assert py_map.global_frame_id == 'odom'
        assert py_map.origin_x == -1.0
        assert py_map.origin_y == -1.0
        assert py_map.costmap[0] == 255
        assert py_map.costmap.shape == (25,)

    def test_costmap_data_conversion(self):
        """Verify that the data is correctly converted to a numpy uint8 array."""
        msg = OccupancyGrid()
        msg.info.width = 2
        msg.info.height = 2
        # OccupancyGrid data is typically int8 (-1 to 100)
        # We check if your constructor handles the cast to uint8 correctly
        msg.data = [0, 50, 100, -1]
        py_map = PyCostmap2D(msg)
        # In uint8, -1 becomes 255
        expected_array = np.array([0, 50, 100, 255], dtype=np.uint8)
        np.testing.assert_array_equal(py_map.costmap, expected_array)
