name: Build Lyrical

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Docker build context
      run: |
        mkdir -p /tmp/docker_context/ws/src
        cp -r . /tmp/docker_context/ws/src
        echo 'FROM osrf/ros:lyrical-desktop

        RUN apt-get update && apt-get upgrade -y && apt-get install -y \
          python3-pip \
          python3-colcon-common-extensions \
          python3-vcstool \
          git \
          curl \
          && rm -rf /var/lib/apt/lists/*

        WORKDIR /root/ws

        COPY ws /root/ws

        # Uncomment to add a testing repo for unreleased binary packages
        RUN echo "deb [trusted=yes] http://repo.ros2.org/ubuntu/testing $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-testing.list

        RUN apt-get update && rosdep update && \
          rosdep install --from-paths src --ignore-src -r -y \
          --skip-keys=slam_toolbox

        RUN . /opt/ros/lyrical/setup.sh && \
          colcon build --packages-skip nav2_system_tests && \
          colcon test --packages-skip nav2_system_tests && \
          colcon test-result --verbose' > /tmp/docker_context/Dockerfile

    - name: Build Docker image
      run: |
        docker build -t nav2-lyrical /tmp/docker_context
