name: Codespell
on:
  pull_request:

jobs:
  codespell:
    name: Run codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: codespell --config tools/pyproject.toml
