name: GH Action Cache Eviction Policy

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  clean-ghac:
    name: Delete old unused action caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge

          # loop until the list is empty, because it deletes only 30 per page
          has_items=true
          while [ "$has_items" = true ]
          do
            echo "Fetching list of cache key"
            cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
            if [ -z "$cache_keys" ]; then
              has_items=false
            fi

            ## Setting this to not fail the workflow while deleting cache keys. 
            set +e
            echo "Deleting caches..."
            for cacheKey in $cacheKeysForPR
            do
                gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
            done
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
